version: '2'
services:
  mysql:
    image: 'mysql:5.7.24'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${DB_WP_PW}
    volumes:
      - db:/var/lib/mysql

  memcached:
    image: memcached

  wordpress:
    image: 'ltdcox/wordpress:ubuntu1804'
    ports:
      - ${WP_PORT}:80
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${DB_WP_PW}
      - WORDPRESS_SITEURL=${DOCKER_HOST}:${WP_PORT}
    depends_on:
      gitnode:
        condition: service_healthy

  gitnode:
    image: 'ltdcox/gitnode'
    environment:
      - GITHUB_ORG=${ORG}
      - GITHUB_REPO=${REPO}
      - GITHUB_BRANCH=${BRANCH}
      - GITHUB_NAME=${NAME}
      - GITHUB_EMAIL=#{EMAIL_ADDRESS}
    healthcheck:
      test: "exit 0"
    depends_on:
      - mysql
