version: '2'
services:
  mysql:
    image: 'mysql:5.7.24'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${DB_PASSWORD}

  memcached:
    image: memcached

  wordpress:
    image: 'ltdcox/wordpress:ubuntu1804'
    ports:
      - ${WEB_PORT}:80
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_SITEURL=${DOCKER_HOST}:${WEB_PORT}
    depends_on:
      - gitnode

  gitnode:
    image: 'ltdcox/gitnode'
    environment:
      - GITHUB_ORG=${ORG}
      - GITHUB_REPO=${REPO}
      - GITHUB_BRANCH=${BRANCH}
      - GITHUB_NAME=${DEV_NAME}
      - GITHUB_EMAIL=${DEV_EMAIL}
      - GULP_BUILD_TASK=${BUILD_TASK}
    depends_on:
      - mysql
